INSERT INTO cms_content (
cms_content.id,
cms_content.app_id,
cms_content.content_url,
cms_content.content_details,
cms_content.content_keyword,
cms_content.content_description,
cms_content.content_img,
cms_content.content_sort,
cms_content.content_datetime,
cms_content.content_source,
cms_content.content_author,
cms_content.content_display,
cms_content.content_type,
cms_content.content_category_id,
cms_content.content_title,
cms_content.content_hit

)
SELECT
basic.basic_id,
cms_article.article_webid,
cms_article.article_url,
cms_article.article_content,
cms_article.article_keyword,
basic.basic_description,
basic.basic_thumbnails,
basic.basic_sort,
basic.basic_datetime,
cms_article.article_source,
cms_article.article_author,
basic.basic_display,
cms_article.article_type,
basic.basic_categoryid,
basic.basic_title,
basic.basic_hit
FROM
basic
INNER JOIN cms_article ON cms_article.article_basicid = basic.basic_id
