set FOREIGN_KEY_CHECKS=0;
UPDATE model  SET MODEL_URL = 'mdiy/search/index.do?modelName=cms' WHERE MODEL_URL = 'mdiy/search/list.do' OR MODEL_URL='mdiy/search/list.do?modelName=cms';
UPDATE model  SET MODEL_URL = 'mdiy/page/index.do' WHERE MODEL_URL = 'mdiy/modeltemplate/list.do';
UPDATE model  SET MODEL_URL = 'mdiy/contentModel/index.do' WHERE MODEL_URL = 'mdiy/contentModel/list.do';
UPDATE model  SET MODEL_URL = 'mdiy/form/index.do' WHERE MODEL_URL = 'mdiy/diyForm/form/list.do';
UPDATE model  SET MODEL_URL = 'column/index.do' WHERE MODEL_URL = 'cms/column/list.do';
UPDATE model  SET MODEL_URL = 'mall/column/index.do' WHERE MODEL_URL = 'cms/column/list.do' AND MODEL_CODE='06990000';

ALTER TABLE cms_column RENAME TO basic_column;
ALTER TABLE basic_column CHANGE COLUMN_CATEGORYID `COLUMN_CATEGORY_ID` int(22) NOT NULL DEFAULT '0' COMMENT '关联category表（类别表ID）';
ALTER TABLE basic_column CHANGE COLUMN_CONTENTMODELID `COLUMN_CM_ID` int(11) DEFAULT '0' COMMENT '栏目管理的内容模型id';
ALTER TABLE basic_column DROP COLUMN `COLUMN_TENTMODELID`;
ALTER TABLE basic_column DROP COLUMN `COLUMN_WEBSITEID`;

ALTER TABLE model_template RENAME TO mdiy_page;
ALTER TABLE mdiy_page CHANGE mt_id page_id int(11)  NOT NULL AUTO_INCREMENT COMMENT '自增长id';
ALTER TABLE mdiy_page CHANGE mt_modelID page_model_id  int(11) DEFAULT NULL COMMENT '模块id';
ALTER TABLE mdiy_page CHANGE mt_appID page_app_id  int(11) DEFAULT NULL COMMENT '应用id';
ALTER TABLE mdiy_page CHANGE mt_path page_path  varchar(255) DEFAULT NULL COMMENT '自定义页面绑定模板的路径';
ALTER TABLE mdiy_page CHANGE mt_title page_title varchar(255) DEFAULT NULL COMMENT '自定义页面标题';
ALTER TABLE mdiy_page CHANGE mt_key page_key varchar(255) DEFAULT NULL COMMENT '自定义页面访问路径';
ALTER TABLE mdiy_page DROP INDEX mt_key;
ALTER TABLE mdiy_page ADD INDEX index_page_key(page_key);
ALTER TABLE mdiy_page DROP INDEX mt_appID;
ALTER TABLE mdiy_page ADD INDEX index_page_app_id(page_app_id);
ALTER TABLE mdiy_page DROP INDEX mt_modelID;
ALTER TABLE mdiy_page add INDEX index_page_model_id(page_model_id);
ALTER TABLE `mdiy_content_model` ADD COLUMN `CM_APP_ID` int(0) COMMENT '应用编号' AFTER `CM_MODEL_ID`;
ALTER TABLE `mdiy_content_model` DROP COLUMN `CM_MANAGERID`;
ALTER TABLE `mdiy_content_model` CHANGE CM_TIPSNAME CM_TIPS_NAME varchar(30) NOT NULL COMMENT '表单提示文字';
ALTER TABLE `mdiy_content_model` CHANGE CM_TABLENAME CM_TABLE_NAME  varchar(20) NOT NULL COMMENT '表单名称';

ALTER TABLE diy_form RENAME TO mdiy_form;
ALTER TABLE mdiy_form CHANGE DF_ID `FORM_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增长id';
ALTER TABLE mdiy_form CHANGE DF_TIPSNAME `FORM_TIPS_NAME` varchar(30) NOT NULL COMMENT '自定义表单提示文字';
ALTER TABLE mdiy_form CHANGE DF_TABLENAME `FORM_TABLE_NAME` varchar(20) NOT NULL COMMENT '自定义表单表名';
ALTER TABLE mdiy_form CHANGE DF_APPID `FORM_APP_ID` int(11) DEFAULT NULL COMMENT '自定义表单关联的应用编号';
ALTER TABLE `mdiy_form` ADD COLUMN `CREATE_BY` int(11) DEFAULT '0' COMMENT '创建者';
ALTER TABLE `mdiy_form` ADD COLUMN `CREATE_DATE` datetime  COMMENT '创建时间';
ALTER TABLE `mdiy_form` ADD COLUMN `UPDATE_BY` int(11)  DEFAULT '0' COMMENT '更新者';
ALTER TABLE `mdiy_form` ADD COLUMN `UPDATE_DATE` datetime  COMMENT '更新时间';

ALTER TABLE diy_form_field RENAME TO mdiy_form_field;
ALTER TABLE mdiy_form_field CHANGE DFF_ID `FF_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '字段自增长id';
ALTER TABLE mdiy_form_field CHANGE DFF_TIPSNAME `FF_TIPSNAME` varchar(30) DEFAULT NULL COMMENT '字段提示文字';
ALTER TABLE mdiy_form_field CHANGE DFF_FIELDNAME `FF_FIELDNAME` varchar(20) DEFAULT NULL COMMENT '字段名称';
ALTER TABLE mdiy_form_field CHANGE DFF_TYPE `FF_TYPE` int(11) DEFAULT NULL COMMENT '字段类型（如1.单行，2.多行，3.图片，等）';
ALTER TABLE mdiy_form_field CHANGE DFF_DEFAULT `FF_DEFAULT` varchar(250) DEFAULT NULL COMMENT '字段的默认值';
ALTER TABLE mdiy_form_field CHANGE DFF_ISNULL `FF_ISNULL` int(11) DEFAULT NULL COMMENT '字段是否为空';
ALTER TABLE mdiy_form_field CHANGE DFF_SORT `FF_SORT` int(11) DEFAULT NULL COMMENT '自定义表单的排序';
ALTER TABLE mdiy_form_field CHANGE DFF_FORMID `FF_FORMID` int(11) DEFAULT NULL COMMENT '字段管理的表单id';
ALTER TABLE `mdiy_form_field` ADD COLUMN `CREATE_BY` int(11) DEFAULT '0' COMMENT '创建者';
ALTER TABLE `mdiy_form_field` ADD COLUMN `CREATE_DATE` datetime  COMMENT '创建时间';
ALTER TABLE `mdiy_form_field` ADD COLUMN `UPDATE_BY` int(11)  DEFAULT '0' COMMENT '更新者';
ALTER TABLE `mdiy_form_field` ADD COLUMN `UPDATE_DATE` datetime  COMMENT '更新时间';

ALTER TABLE mdiy_search CHANGE SEARCH_WEBSITEID `SEARCH_APP_ID` int(11) NOT NULL COMMENT '搜索管理的应用id';

ALTER TABLE basic_attention CHANGE ba_peopleID ba_people_id  int(11) DEFAULT NULL COMMENT '用户id';
ALTER TABLE basic_attention CHANGE ba_appID ba_app_id  int(11) DEFAULT NULL COMMENT '用户应用id';
ALTER TABLE basic_attention CHANGE ba_basicID ba_basic_id  int(11) DEFAULT NULL COMMENT '用户收藏关联的基础id';

ALTER TABLE `comment` ENGINE = InnoDB;
ALTER TABLE `cms_article` ENGINE = InnoDB;
ALTER TABLE `app` ENGINE = InnoDB;
ALTER TABLE `basic_attention` ENGINE = InnoDB;
ALTER TABLE `role` CHANGE ROLE_ID `ROLE_ID`  int(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID，自增长';
ALTER TABLE `manager` CHANGE MANAGER_ROLEID `MANAGER_ROLEID`  int(11) DEFAULT NULL COMMENT '角色编号';
ALTER TABLE `manager` CHANGE MANAGER_ID `MANAGER_ID`  int(11) NOT NULL AUTO_INCREMENT COMMENT '管理员ID(主键)';
ALTER TABLE `app` ADD CONSTRAINT `fk_app_manager_1` FOREIGN KEY (`APP_MANAGERID`) REFERENCES `manager` (`MANAGER_ID`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `basic` ADD CONSTRAINT `fk_basic_category_1` FOREIGN KEY (`BASIC_CATEGORYID`) REFERENCES `category` (`CATEGORY_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `basic` ADD CONSTRAINT `fk_basic_app_1` FOREIGN KEY (`BASIC_APPID`) REFERENCES `app` (`APP_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `basic_attention` ADD CONSTRAINT `fk_basic_attention_basic_1` FOREIGN KEY (`ba_basic_id`) REFERENCES `basic` (`BASIC_ID`) ON DELETE CASCADE;
ALTER TABLE `basic_column` ADD CONSTRAINT `fk_basic_column` FOREIGN KEY (`COLUMN_CATEGORY_ID`) REFERENCES `category` (`CATEGORY_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `basic_log` ADD CONSTRAINT `fk_basic_log_basic_1` FOREIGN KEY (`bl_basic_id`) REFERENCES `basic` (`BASIC_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `category` ADD CONSTRAINT `fk_category` FOREIGN KEY (`CATEGORY_CATEGORYID`) REFERENCES `category` (`CATEGORY_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `category` ADD CONSTRAINT `fk_category_1` FOREIGN KEY (`CATEGORY_APPID`) REFERENCES `app` (`APP_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `manager` ADD COLUMN `MANAGER_SYSTEM_SKIN_ID` int NULL DEFAULT 0 COMMENT '管理员主界面样式' AFTER `MANAGER_TIME`;


ALTER TABLE `manager` ADD CONSTRAINT `fk_manager_role_1` FOREIGN KEY (`MANAGER_ROLEID`) REFERENCES `role` (`ROLE_ID`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `manager_model_page` CHANGE mmp_modelID `mmp_model_id` int(11) NULL DEFAULT NULL COMMENT '模块编号';
ALTER TABLE `manager_model_page` CHANGE mmp_managerID `mmp_manager_id` int(11) NULL DEFAULT NULL COMMENT '自增长id';
ALTER TABLE `manager_model_page` ADD CONSTRAINT `fk_manager_model_page_manager_1` FOREIGN KEY (`mmp_manager_id`) REFERENCES `manager` (`MANAGER_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `manager_model_page` ADD CONSTRAINT `fk_manager_model_page_model_1` FOREIGN KEY (`mmp_model_id`) REFERENCES `model` (`MODEL_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE `role_model` DROP FOREIGN KEY `role_model_ibfk_1`;
ALTER TABLE `role_model` ADD CONSTRAINT `role_model_ibfk_1` FOREIGN KEY (`RM_MODELID`) REFERENCES `model` (`MODEL_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `role_model` ADD CONSTRAINT `fk_role_model_role_1` FOREIGN KEY (`RM_ROLEID`) REFERENCES `role` (`ROLE_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `system_skin` CHANGE  ss_appID `ss_app_id` int(11) NULL DEFAULT NULL COMMENT '0后台发布大于０表示是应用自定义';
ALTER TABLE `system_skin` CHANGE ss_categoryID `ss_category_id` int(11) NULL DEFAULT NULL COMMENT '主题分类';
ALTER TABLE `system_skin` ADD CONSTRAINT `fk_system_skin_app_1` FOREIGN KEY (`ss_app_id`) REFERENCES `app` (`APP_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `basic` MODIFY COLUMN `BASIC_APPID` int(11) NOT NULL COMMENT '应用编号' AFTER `BASIC_CATEGORYID`;
DROP INDEX `SYS_C009068` ON `basic`;
CREATE UNIQUE INDEX `BASIC_ID` ON `basic` (`BASIC_ID` ASC);
ALTER TABLE `category` MODIFY COLUMN `CATEGORY_SMALLIMG` varchar(2000) NULL DEFAULT NULL COMMENT '略缩图' AFTER `CATEGORY_CATEGORYID`;
ALTER TABLE `category` MODIFY COLUMN `CATEGORY_CATEGORYID` int(11) NULL DEFAULT NULL COMMENT '父类别编号' AFTER `CATEGORY_MODELID`;
ALTER TABLE `category` ADD COLUMN `CREATE_BY` int(11) NULL DEFAULT 0 COMMENT '创建人' AFTER `CATEGORY_DICT_ID`;
ALTER TABLE `category` ADD COLUMN `CREATE_DATE` datetime NULL DEFAULT NULL COMMENT '创建时间' AFTER `CREATE_BY`;
ALTER TABLE `category` ADD COLUMN `UPDATE_BY` int(11) NULL DEFAULT 0 COMMENT '更新人' AFTER `CREATE_DATE`;
ALTER TABLE `category` ADD COLUMN `UPDATE_DATE` datetime NULL DEFAULT NULL COMMENT '更新时间' AFTER `UPDATE_BY`;
ALTER TABLE `category` ADD COLUMN `DEL` int(11) NOT NULL DEFAULT 0 COMMENT '删除状态' AFTER `UPDATE_DATE`;


DROP INDEX `BASIC_DATETIME` ON `basic`;
ALTER TABLE `category` DROP COLUMN `CATEGORY_CREATE_BY`;
ALTER TABLE `category` DROP COLUMN `CATEGORY_CREATE_DATE`;
ALTER TABLE `category` DROP COLUMN `CATEGORY_UPDATE_BY`;
ALTER TABLE `category` DROP COLUMN `CATEGORY_UPDATE_DATE`;
ALTER TABLE `category` DROP COLUMN `CATEGORY_DEL`;
ALTER TABLE `role` MODIFY COLUMN `ROLE_MANAGERID` int(11) NULL DEFAULT 0 COMMENT '角色管理员编号' AFTER `ROLE_NAME`;
ALTER TABLE `system_skin` DROP COLUMN `ss_loginpage`;
ALTER TABLE `model` MODIFY COLUMN `MODEL_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '模块自增长id' FIRST;
ALTER TABLE `manager_model_page` COMMENT = '管理员对应的每个模块的主界面自定义';


ALTER TABLE `mdiy_form_field` ENGINE = InnoDB;
ALTER TABLE `mdiy_form` ENGINE = InnoDB;
ALTER TABLE `mdiy_page` ENGINE = InnoDB;
ALTER TABLE `mdiy_content_model` ENGINE = InnoDB;
ALTER TABLE `mdiy_content_mode_field` ENGINE = InnoDB;
ALTER TABLE `basic_column` ADD CONSTRAINT `fk_basic_column_1` FOREIGN KEY (`COLUMN_CM_ID`) REFERENCES `mdiy_content_model` (`CM_ID`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `mdiy_content_mode_field` ADD CONSTRAINT `fk_mdiy_content_mode_field_mdiy_content_model_1` FOREIGN KEY (`FIELD_CMID`) REFERENCES `mdiy_content_model` (`CM_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `mdiy_content_model` ADD CONSTRAINT `fk_mdiy_content_model` FOREIGN KEY (`CM_APP_ID`) REFERENCES `app` (`APP_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `mdiy_form` DROP COLUMN `DF_MANAGERID`;
ALTER TABLE `mdiy_form` MODIFY COLUMN `FORM_APP_ID` int(11) NOT NULL COMMENT '自定义表单关联的应用编号' AFTER `FORM_TABLE_NAME`;
ALTER TABLE `mdiy_form` MODIFY COLUMN `CREATE_BY` int(11) NULL AFTER `FORM_APP_ID`;	
ALTER TABLE `mdiy_form` MODIFY COLUMN `CREATE_DATE` datetime NULL ;
ALTER TABLE `mdiy_form` MODIFY COLUMN `UPDATE_BY` int(11) NULL AFTER `CREATE_DATE`;
ALTER TABLE `mdiy_form` MODIFY COLUMN `UPDATE_DATE` datetime NULL ;
ALTER TABLE `mdiy_form` ADD CONSTRAINT `fk_mdiy_form` FOREIGN KEY (`FORM_APP_ID`) REFERENCES `app` (`APP_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `mdiy_form_field` ADD CONSTRAINT `fk_mdiy_form_field` FOREIGN KEY (`FF_FORMID`) REFERENCES `mdiy_form` (`FORM_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `mdiy_page` ADD CONSTRAINT `fk_model_template_app_1` FOREIGN KEY (`page_app_id`) REFERENCES `app` (`APP_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `mdiy_search` ADD CONSTRAINT `fk_mdiy_search` FOREIGN KEY (`SEARCH_APP_ID`) REFERENCES `app` (`APP_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `mdiy_search` MODIFY COLUMN `SEARCH_TYPE` varchar(20) NOT NULL DEFAULT 'cms' COMMENT '搜索类型' AFTER `SEARCH_APP_ID`;

ALTER TABLE `mdiy_content_model` ADD COLUMN `CREATE_BY` int(255) NULL AFTER `CM_APP_ID`;
ALTER TABLE `mdiy_content_model` ADD COLUMN `CREAET_DATE` datetime NULL ;
ALTER TABLE `mdiy_content_model` ADD COLUMN `UPDATE_BY` int NULL AFTER `CREAET_DATE`;	
ALTER TABLE `mdiy_content_model` ADD COLUMN `UPDATE_DATE` datetime NULL ;
CREATE TABLE `mdiy_dict` (
`dict_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
`app_id` int NULL COMMENT '应用编号',
`dict_value` varchar(100) NOT NULL COMMENT '数据值',
`dict_label` varchar(100) NOT NULL COMMENT '标签名',
`dict_type` varchar(100) NOT NULL COMMENT '类型',
`dict_description` varchar(100) NOT NULL COMMENT '描述',
`dict_sort` int(10) NOT NULL DEFAULT 0 COMMENT '排序（升序）',
`dict_parent_id` varchar(64) NULL DEFAULT '0' COMMENT '父级编号',
`dict_remarks` varchar(255) NULL DEFAULT NULL COMMENT '备注信息',
`create_by` int(64) NULL DEFAULT 0 COMMENT '创建者',
`create_date` datetime NULL COMMENT '创建时间',
`update_by` int(64) NULL DEFAULT 0 COMMENT '更新者',
`update_date` datetime NULL DEFAULT NULL COMMENT '更新时间',
`del` int(1) NOT NULL DEFAULT 0 COMMENT '删除标记',
PRIMARY KEY (`dict_id`) 
)
ENGINE = InnoDB
COMMENT = '字典表';
ALTER TABLE `mdiy_dict` ADD CONSTRAINT `fk_mdiy_dict` FOREIGN KEY (`app_id`) REFERENCES `app` (`APP_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `mdiy_content_mode_field` ADD COLUMN `CREATE_BY` int(11) NULL AFTER `FIELD_LENGTH`;
ALTER TABLE `mdiy_content_mode_field` ADD COLUMN `CREATE_DATE` datetime NULL ;
ALTER TABLE `mdiy_content_mode_field` ADD COLUMN `UPDATE_BY` int(11) NULL AFTER `CREATE_DATE`;
ALTER TABLE `mdiy_content_mode_field` ADD COLUMN `UPDATE_DATE` datetime NULL;
ALTER TABLE `mdiy_content_mode_field` ADD COLUMN `DEL` int(1) NULL AFTER `UPDATE_DATE`;
ALTER TABLE `mdiy_form_field` DROP COLUMN `CREATE_BY`;
ALTER TABLE `mdiy_form_field` DROP COLUMN `CREATE_DATE`;
ALTER TABLE `mdiy_form_field` DROP COLUMN `UPDATE_BY`;
ALTER TABLE `mdiy_form_field` DROP COLUMN `UPDATE_DATE`;

ALTER TABLE `people` MODIFY COLUMN `PEOPLE_CODESENDDATE` datetime NULL COMMENT '发送验证码时间' AFTER `PEOPLE_CODE`;
ALTER TABLE `people` MODIFY COLUMN `PEOPLE_PHONECHECK` int(1) NULL DEFAULT 0 COMMENT '1手机验证通过' AFTER `PEOPLE_CODESENDDATE`;
ALTER TABLE `people` ADD CONSTRAINT `fk_people` FOREIGN KEY (`PEOPLE_APP_ID`) REFERENCES .`app` (`APP_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `people_user` ADD CONSTRAINT `fk_people_user_people_1` FOREIGN KEY (`PU_PEOPLE_ID`) REFERENCES .`people` (`PEOPLE_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;


ALTER TABLE `comment` ADD COLUMN `COMMENT_IS_ANONYMOUS` int(11) NULL DEFAULT 0 COMMENT '是否匿名' AFTER `COMMENT_FILE_PATH`;
ALTER TABLE `comment` ADD COLUMN `COMMENT_AUDIT` int(1) NULL DEFAULT 0 COMMENT '0默认显示 1:审核不通过' AFTER `COMMENT_IS_ANONYMOUS`;
ALTER TABLE `comment` ADD CONSTRAINT `fk_comment` FOREIGN KEY (`COMMENT_BASICID`) REFERENCES .`basic` (`BASIC_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `comment` ADD CONSTRAINT `fk_comment_people_1` FOREIGN KEY (`COMMENT_PEOPLEID`) REFERENCES .`people` (`PEOPLE_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `people` MODIFY COLUMN `PEOPLE_MAILLCHECK` int(1) NULL DEFAULT 0 COMMENT '1邮箱验证通过' AFTER `PEOPLE_PHONECHECK`;
ALTER TABLE `people` MODIFY COLUMN `PEOPLE_DATETIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间' AFTER `PEOPLE_PASSWORD`;
ALTER TABLE cms_article ADD CONSTRAINT `fk_cms_article_basic_1` FOREIGN KEY (`ARTICLE_BASICID`) REFERENCES .`basic` (`BASIC_ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
DROP TABLE `system_skin_manager`;
DROP TABLE `system_main_page`;
DROP TABLE `basic_child`;
DROP TABLE `basic_category`;
DROP TABLE `basic_type`;
DROP VIEW `v_article`;
DROP VIEW `v_people_user`;
DROP TABLE `dict`;
set FOREIGN_KEY_CHECKS=1;