/*! Copyright 2015 Baidu Inc. All Rights Reserved. */;(function(){var l=void 0,m=!0,q=null,r=!1;function s(a){return function(){return a}}var u={t1:+new Date,t2:0,t3:0,t4:0},y=["search!"],ga=3,ha="BAIDU_DUP_replacement",ia="http://dup.baidustatic.com/painter/",z=document,C={},ja=0,ka=1,D=2,E=3,F=4,la=5;function ma(a){var b=na(a),d=b[0],b=b[1];this.id=a;this.name=b;this.uri=G(b);this.Fa=!b;this.status=ja;d&&b&&(this.Ka=J(K(d+"!"))||{load:function(){}});this.v=[]}
var Q=window.BAIDU_DUP_require||function(a,b,d){L(a,function(){for(var c=[],d=0;d<a.length;d++)c[d]=J(K(a[d]));P(b)&&b.apply(window,c)},d)};
function L(a,b,d){var c=a.length;if(0===c)b();else for(var k=c,f=0;f<c;f++)(function(a){function i(){if(a.status<D)j();else{for(var i=a.v,c=[],b=0;b<i.length;b++){var h=i[b];h&&K(h).status<E&&c.push(h)}0===c.length?j():L(c,j,d)}}function j(){a&&a.status<E&&(a.status=E);0===--k&&b()}var c=a.Ka;c&&(c.normalize&&(a.name=c.normalize(a.name,G)),c.name2url&&(a.uri=c.name2url(a.name)));a.status<D?c&&P(c.load)?c.load(a.name,Q,function(i){R(a.id,[],function(){return i});j()}):oa(a,i,d):i()})(K(a[f]))}
var S={},T={},U={};function oa(a,b,d){a.status=ka;U[a.id]?b():T[a.id]?S[a.id].push(b):(T[a.id]=m,S[a.id]=[b],0===a.uri.indexOf("http://cb.baidu.com/ecom?")&&(u.t2=+new Date),d?(b=a.uri,a=z.createElement("script"),a.charset="utf-8",a.async=m,a.src=b,b=z.getElementsByTagName("head")[0]||z.body,b.insertBefore(a,b.firstChild)):z.write('<script charset="utf-8" src="'+a.uri+'"><\/script>'))}
var R=window.BAIDU_DUP_define||function(a,b,d){8<a.length&&0===a.indexOf("request!")&&(u.t3=+new Date);var c=K(a);c.status<D&&(c.v=b,c.factory=d,c.status=c.Fa?E:D);if(T[a]){delete T[a];U[a]=m;b=S[a];for(delete S[a];a=b.shift();)a()}};function J(a){if(!a)return q;if(a.status>=F)return a.X;if(a.status<E&&a.X===l)return q;a.status=F;for(var b=[],d=0;d<a.v.length;d++)b[d]=J(K(a.v[d]));var c=d=a.factory;P(d)&&(c=d.apply(window,b));a.status=la;return a.X=c}
function G(a){return/^https?:\/\//.test(a)?a:ia+a+".js"}function K(a){return C[a]||(C[a]=new ma(a))}function na(a){var b,d=a?a.indexOf("!"):-1;-1<d&&(b=a.slice(0,d),a=a.slice(d+1,a.length));return[b,a]}function P(a){return"[object Function]"===Object.prototype.toString.call(a)}
R("util/lang",[],function(){function a(a){for(var c={},b="Array Boolean Date Error Function Number RegExp String".split(" "),f=0,g=b.length;f<g;f++)c["[object "+b[f]+"]"]=b[f].toLowerCase();return a==q?"null":c[Object.prototype.toString.call(a)]||"object"}var b=Object.prototype.hasOwnProperty;return{B:b,b:a,getAttribute:function(a,c){for(var b=a,f=c.split(".");f.length;){if(b===l||b===q)return;b=b[f.shift()]}return b},ia:function(d){if("object"!==a(d))return"";var c=[],k;for(k in d)b.call(d,k)&&c.push(k+
"="+encodeURIComponent(d[k]));return c.join("&")},l:function(b){var c=[];switch(a(b)){case "object":c=Array.prototype.slice.call(b);break;case "array":c=b;break;case "number":case "string":c.push(b)}return c},unique:function(a){for(var c=[],b={},f=a.length,g=0;g<f;g++){var i=a[g];b[i]||(c[c.length]=i,b[i]=m)}return c},removeItem:function(a,c){for(var b=[].slice.call(a),f=b.length-1;0<=f;f--)b[f]===c&&b.splice(f,1);return b},fa:function(){}}});
R("util/browser",["util/lang"],function(a){var b={},d=navigator.userAgent,c=window.RegExp;/msie (\d+\.\d)/i.test(d)&&(b.s=document.documentMode||+c.$1);/opera\/(\d+\.\d)/i.test(d)&&(b.opera=+c.$1);/firefox\/(\d+\.\d)/i.test(d)&&(b.Xa=+c.$1);/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(d)&&!/chrome/i.test(d)&&(b.ib=+(c.$1||c.$2));if(/chrome\/(\d+\.\d)/i.test(d)){b.qa=+c.$1;var k;try{k="scoped"in document.createElement("style")}catch(f){k=r}k&&(b.Pa=m)}try{/(\d+\.\d)/.test(a.getAttribute(window,
"external.max_version"))&&(b.cb=+c.$1)}catch(g){}a="Android iPad iPhone Linux Macintosh Windows".split(" ");c="";for(k=0;k<a.length&&!(c=a[k],d.match(RegExp(c.toLowerCase(),"i")));k++);b.platform=c;return b});
R("util/dom",["util/lang"],function(a){function b(a){try{if(a&&"object"===typeof a&&a.document&&"setInterval"in a)return m}catch(i){}return r}function d(a,i){i=2===arguments.length?i:a.parent;return a!=i||!b(a)}function c(a,i){for(var i=2===arguments.length?i:a.parent,j=0;10>j++&&d(a,i);){var c;try{c=!!a.parent.location.toString()}catch(b){c=r}if(!c)return m;a=a.parent}return 10<=j}function k(a){return 9===a.nodeType?a:a.ownerDocument||a.document}function f(b,i){1===arguments.length&&"number"===a.b(arguments[0])&&
(i=arguments[0],b=l);for(var i=i||10,j=window,h=0;h++<i&&d(j)&&!c(j)&&(!b||!b(j));)j=j.parent;return j}return{c:function(c,i){return"string"===a.b(c)&&0<c.length?(i||window).document.getElementById(c):c.nodeName&&(1===c.nodeType||9===c.nodeType)?c:q},Ga:b,t:d,C:c,va:k,Z:function(){var a=f().document.title;60<a.length&&(a=a.substr(0,60));return a},A:function(a){a=k(a);return a.parentWindow||a.defaultView||q},j:function(a){a=b(a)?a.document:k(a);return"CSS1Compat"===a.compatMode?a.documentElement:a.body},
L:f}});
R("util/style",["util/lang","util/dom","util/browser"],function(a,b,d){function c(a,c){if(!a)return"";var h="",h=-1<c.indexOf("-")?c.replace(/[-][^-]{1}/g,function(a){return a.charAt(1).toUpperCase()}):c.replace(/[A-Z]{1}/g,function(a){return"-"+a.charAt(0).toLowerCase()}),e=b.A(a);if(e&&e.getComputedStyle){if(e=e.getComputedStyle(a,q))return e.getPropertyValue(c)||e.getPropertyValue(h)}else if(a.currentStyle)return e=a.currentStyle,e[c]||e[h];return""}function k(a){var j={top:0,left:0};if(a===b.j(a))return j;
var h=b.va(a),e=h.body,h=h.documentElement;a.getBoundingClientRect&&(a=a.getBoundingClientRect(),j.left=Math.floor(a.left)+Math.max(h.scrollLeft,e.scrollLeft),j.top=Math.floor(a.top)+Math.max(h.scrollTop,e.scrollTop),j.left-=h.clientLeft,j.top-=h.clientTop,a=c(e,"borderLeftWidth"),e=c(e,"borderTopWidth"),a=parseInt(a,10),e=parseInt(e,10),j.left-=isNaN(a)?2:a,j.top-=isNaN(e)?2:e);return j}function f(a,j){var b=c(a,"margin"+j).toString().toLowerCase().replace("px","").replace("auto","0");return parseInt(b,
10)||0}function g(c){for(var j=b.A(c),h=100;c&&c.tagName;){var e=100;if(d.s){if(5<d.s)try{e=parseInt(a.getAttribute(c,"filters.alpha.opacity"),10)||100}catch(f){}h=h>e?e:h}else{try{e=100*(j.getComputedStyle(c,q).opacity||1)}catch(n){}h*=e/100}c=c.parentNode}return 0===h?0:h||100}return{ab:c,$a:k,r:function(a){var c=b.c(a);if(!c)return r;a=k(c);c=b.A(c);if(!c)return a;for(var d=0;c!==c.parent&&10>d++&&!b.C(c)&&c.frameElement;){var e=k(c.frameElement);a.left+=e.left;a.top+=e.top;c=c.parent}return a},
Ya:f,N:function(a,c){var d=b.c(a),e=d.offsetWidth;c&&(e+=f(d,"Left")+f(d,"Right"));return e},M:function(a,c){var d=b.c(a),e=d.offsetHeight;c&&(e+=f(d,"Top")+f(d,"Bottom"));return e},Za:g,xa:function(a){for(var c=b.c(a),a=b.A(c),c=g(c),d=0;10>d++&&b.t(a)&&!b.C(a);){var e=a.frameElement?g(a.frameElement):100,c=c*(e/100);a=a.parent}return c},ca:function(a){try{var c=b.j(a||window).scrollWidth;if(c||0===c)return c}catch(d){}return-1},ba:function(a){try{var c=b.j(a||window).scrollHeight;if(c||0===c)return c}catch(d){}return-1},
p:function(a){try{var c=b.j(a||window).clientWidth;if(c||0===c)return c}catch(d){}return-1},o:function(a){try{var c=b.j(a||window).clientHeight;if(c||0===c)return c}catch(d){}return-1},Ba:function(a){var c=b.j(a);return a.pageYOffset||c.scrollTop},Aa:function(a){var c=b.j(a);return a.pageXOffset||c.scrollLeft}}});
R("util/url",["util/dom"],function(a){return{aa:function(a,d,c){a=a.match(RegExp("(\\?|&|#)"+d+"=([^&#]*)(&|#)?"));d="";a&&(d=a[2]);c&&(d=decodeURIComponent(d));return d},O:function(b){var b=a.L(b),d="";a.t(b)&&(d=b.document.referrer);return d=d||b.location.href}}});
R("util/event",["util/dom"],function(a){return{bind:function(b,d,c){if(b=a.Ga(b)?b:a.c(b))if(b.addEventListener)b.addEventListener(d,c,r);else if(b.attachEvent)b.attachEvent("on"+d,c);else{var k=b["on"+d];b["on"+d]=function(){k&&k.apply(this,arguments);c.apply(this,arguments)}}return b}}});
R("util/cookie",["util/lang"],function(a){return{get:function(a,d){var c=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie);return c?d?decodeURIComponent(c[2]):c[2]:""},set:function(b,d,c,k){var f=c.expires;"number"===a.b(f)&&(f=new Date,f.setTime(+f+c.expires));document.cookie=b+"="+(k?encodeURIComponent(d):d)+(c.path?"; path="+c.path:"")+(f?"; expires="+f.toGMTString():"")+(c.domain?"; domain="+c.domain:"")}}});
R("util/data",["util/lang","util/dom"],function(a,b){function d(c,b,e){var e=e?i:f,d;if("string"===a.b(c)){for(c=c.split(".");c.length;)d=c.shift(),e[d]=c.length?e[d]!==l?e[d]:{}:b,e=e[d];d=b}return d}function c(c,b){var e=b?i:f,d;"string"===a.b(c)&&(d=a.getAttribute(e,c));return d}function k(a,b,e){if(!a||!b)return r;var i=c(a)||{};switch(e){case "+1":e=i[b]||0;i[b]=++e;break;default:i[b]=parseInt(e,10)}d(a,i);return i[b]}var f={},g=b.L(),i=g.BAIDU_DUP_info||(g.BAIDU_DUP_info={});return{m:function(a,
c){var b=window;return b[a]?b[a]:b[a]=c},q:function(a){var c=window,b=c[a];c[a]=l;return b},f:d,d:c,ha:function(c,b){var d=b?i:f;switch(a.b(c)){case "string":for(var g=c.split(".");g.length;){var n=g.shift();if(g.length&&d[n]!==l)d=d[n];else return delete d[n],m}}return r},U:function(a,c,b){return b?(this.e=this.e||{},this.e[b]=this.e[b]||0,!this.e[b]&&document.getElementById(b)&&(this.e[b]=1),this.e[b]):k(a,c,"+1")},fb:function(a,c,b){return k(a,c,b)},count:k,ua:function(a,b,d){return d?(this.e=
this.e||{},this.e[d]=this.e[d]||0,document.getElementById(d)||delete this.e[d],this.e[d]||0):!a||!b?r:(c(a)||{})[b]||0},Oa:function(a,b){if(!a||!b)return r;var i=c("pageConfig")||{};i[a]=b;d("pageConfig",i);return m},ta:function(a){return!a?r:(c("pageConfig")||{})[a]}}});
R("util/storage",[],function(){function a(a,c,b){if(d)try{d.setItem(a,b?encodeURIComponent(c):c)}catch(i){}}function b(a,c){if(d){var b=d.getItem(a);return c&&b?decodeURIComponent(b):b}return q}var d;try{d=window.localStorage}catch(c){}return{pa:function(){var c=r;try{d.removeItem("BAIDU_DUP_storage_available"),a("BAIDU_DUP_storage_available","1"),b("BAIDU_DUP_storage_available")&&(c=m),d.removeItem("BAIDU_DUP_storage_available")}catch(f){}return c},setItem:a,getItem:b,la:function(c,f,g){if(d){f=
g?encodeURIComponent(f):f;g=b(c)||"";try{a(c,g+((g&&"|")+f))}catch(i){}}},ka:function(c,f,g){if(d)if(f=g?encodeURIComponent(f):f,g=b(c)||"",g=g.replace(RegExp(f+"\\|?","g"),"").replace(/\|$/,""))try{a(c,g)}catch(i){}else d.removeItem(c)}}});
R("util/log",["util/lang","util/event","util/storage"],function(a,b,d){function c(a,c){var b=new Image,d="BAIDU_DUP_log_"+Math.floor(2147483648*Math.random()).toString(36);window[d]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=q;b=window[d]=q;c&&c(k,a,m)};b.src=a}var k="BAIDU_DUP_log_storage";return{bb:c,gb:function(){var a=d.getItem(k);if(a)for(var a=a.split("|"),b=0,i=a.length;b<i;b++)c(decodeURIComponent(a[b]),d.ka)},H:function(f){var f="object"===a.b(f)?f:{},g=f.url||
"http://cbjslog.baidu.com/log",i=f.option||"now",f=a.ia(f.data||{}),g=g+((0<=g.indexOf("?")?"&":"?")+f+(f?"&":"")+"rdm="+ +new Date);switch(i){case "now":c(g);break;case "block":break;default:d.la(k,g,m),b.bind(window,"unload",function(){c(g,d.ka)})}}}});R("util","util/lang,util/dom,util/style,util/url,util/event,util/cookie,util/data,util/storage,util/log,util/browser".split(","),function(a,b,d,c,k,f,g,i,j,h){return{lang:a,a:b,style:d,url:c,event:k,cookie:f,data:g,jb:i,log:j,W:h}});
R("biz",["util","slot"],function(a,b){function d(c,b){var d=/^[0-9a-zA-Z]+$/;return!c||!d.test(c)||!b?[]:b="array"===a.lang.b(b)?b:Array.prototype.slice.call(arguments,1)}function c(c,b,d){if(!b||!b.length)return r;var d=d||{T:r,ea:r,ga:r},h=d.ea?a.data.d(k):{},e=d.T?f:k,h=d.ga?{}:a.data.d(e)||h,d={},o;for(o in h)a.lang.B.call(h,o)&&(d[o]="array"===a.lang.b(h[o])?h[o].slice():h[o]);var h=d[c]||[],n=b.length;for(o=0;o<n;o++){var p=b[o];"string"===typeof p&&(p=encodeURIComponent(p),100>=p.length&&(h[h.length]=
p))}if(!h.length)return r;d[c]=a.lang.unique(h);a.data.f(e,d);return m}var k="bizOrientations",f="bizUrgentOrientations";return{V:function(a,b){var f=d.apply(this,arguments);return c(a,f)},ma:function(a,b){var f=d.apply(this,arguments);return c(a,f,{T:m,ea:m})},Ra:function(a,b){var f=d.apply(this,arguments);return c(a,f,{T:m,ga:m})},ya:function(c){var c=Math.max(0,Math.min(c||500,500)),b=[],d=a.data.d(f)||a.data.d(k)||{};if("object"===a.lang.b(d))for(var h in d)a.lang.B.call(d,h)&&(b[b.length]=h+
"="+d[h].join(","));a.data.f(f,l);b.sort(function(a,c){return a.length-c.length});d="";h=b.length;for(var e=0;e<h&&!(d.length+b[e].length>=c);e++)d+=(e?"&":"")+b[e];return d},na:function(a,c){b.Sa(a);b.oa(c)}}});
R("preview",["biz","util"],function(a,b){function d(){function a(c){var d=b.url.aa;return d(k,"baidu_clb_preview_"+c)||d(k,"baidu_dup_preview_"+c)}var k=b.url.O(),f=a("sid"),g=a("mid"),i=a("vc"),j=+a("ts"),h=q;3E4>=+new Date-j&&(h={ja:f,Ia:g,Ua:i});d=function(){return h};return h}return{Ca:function(a){var b=[],f=d();f&&a==f.ja&&(b.push("mid="+f.Ia),b.push("sid="+f.Ua));return b.join("&")},d:function(){return d()},da:function(a){var d=r;a?/cpro_template=/gi.test(a)&&(b.data.f("#unionPreviewSwitch",
m),d=m):d=!!b.data.d("#unionPreviewSwitch");return d},Da:function(){var a=b.data.d("#unionPreviewData");return a?"prev="+encodeURIComponent(a)+"&pt=union":""},Ta:function(a){b.data.f("#unionPreviewData",a)},Wa:function(){b.data.ha("#unionPreviewSwitch");b.data.ha("#unionPreviewData")}}});
R("slot",["util"],function(a){function b(){for(var a={response:{},holder:"",stack:[],errors:[],status:{}},c=j.length-1;0<=c;c--)a.status[j[c]]=0;return a}function d(a,c){var b=r;"fillAsync"===c&&(b=m);o[a]&&-1!==o[a].stack.join(" ").toLowerCase().indexOf("async")&&(b=m);return b}function c(a,c){if(!a)return"";var b=t+a;c&&(b+="_"+c);return b}function k(a,c,b){if(!a||!c)return r;b===l&&(b=+new Date);if(o[a]){o[a].status[c]=b;if("finish"===c){var c={},b=r,d;for(d in p)if(d&&p.hasOwnProperty(d)&&p[d]&&
0===(""+a).indexOf(""+d)&&o[a].response){var b=o[a].response.data,e=b._h||b.sh||b.height||0;c[a]=0===(b._w||b.sw||b.width||0)||0===e?r:m;b=m}b&&n.apply(window,[c])}return m}return r}function f(a,c){g(a,"errors",c)}function g(c,b,d){c&&b&&d&&(c=o[c])&&"array"===a.lang.b(c[b])&&c[b].push(d)}function i(a){return!a?o:o[a]||r}var j="add,create,request,response,render,finish".split(","),h=[],e={},o={},n,p={},t="BAIDU_DUP_wrapper_";return{add:function(){var c={ids:[],preloadIds:[]},d=a.lang.l(arguments);
if(!d.length)return c;for(var d=d.join(",").split(","),n=[],p=[],f=d.length,t=0;t<f;t++){var g=d[t];if(e.hasOwnProperty(g)){var j=g+"_"+e[g],V=i(j).stack||[];if("preload"===V[V.length-1]){c.preloadIds.push(j);continue}e[g]+=1}else e[g]=0;g=g+"_"+e[g];o[g]=new b;k(g,"add");p.push(g);n.push(g)}h=h.concat(p);c.ids=n;return c},create:function(b,e,n){if(!b||!e)return r;var p=c(b),i=m;if(a.a.c(p))return o[b].holder=p,i;if(d(b,e)){n=n||"";o[b].holder=n;n=a.a.c(n);try{n&&(n.innerHTML='<div id="'+p+'"></div>',
o[b].holder=p)}catch(g){f(b,"Failed to insert wrapper"),i=r}}else if(document.write('<div id="'+p+'"></div>'),!a.a.c(p))try{var h=document.getElementsByTagName("script"),t=h[h.length-1];if(t){var j=t.parentNode;if(j){var W=document.createElement("div");W.id=c(b,"b");j.insertBefore(W,t)}}}catch(qa){f(b,"Failed to create backup wrapper")}k(b,"create");return i},sa:d,wa:function(a){return d(a)?"async":"sync"},$:function(b){return!b?"":(b=a.a.c(o[b].holder)||a.a.c(c(b))||a.a.c(c(b,"b")))&&b.id||""},z:i,
S:function(a,c){if(!a||!c)return r;return o[a]?(o[a].response=c,k(a,"response"),m):r},u:k,k:f,I:function(a,c){g(a,"stack",c)},K:function(c){c=a.lang.l(c);if(!c.length)return r;var b=[],d={},e;for(e=0;e<h.length;e++)d[h[e]]=e+1;for(e=0;e<c.length;e++){var n=d[""+c[e]];n===l&&(n=0);b.push(n)}return b},Sa:function(a){n=a},oa:function(a){p[a]=m},r:function(b){b=a.lang.l(b);if(!b.length)return["-1x-1"];for(var d=[],e=0;e<b.length;e++){var n=b[e],p;try{var i=a.a.c(c(n))||a.a.c(c(n,"b"));if(i){var h=a.style.r(i);
h&&(p=[h.top,h.left])}}catch(g){f(n,"Unable to get ps")}p=p?p:[-1,-1];d.push(p.join("x"))}return d}}});R("api",["slot","util"],function(a,b){return{getDai:a.K,getSlots:a.z,getFillType:a.wa,getFillWrapperId:a.$,setStatus:a.u,addErrorItem:a.k,addStackItem:a.I,bind:b.event.bind,getType:b.lang.b,sendLog:b.log.H,putInfo:b.data.f,getInfo:b.data.d,defineOnce:b.data.m,addCount:b.data.U,getCount:b.data.ua,getConfig:b.data.ta,getDocumentTitle:b.a.Z}});
R("param",["slot","preview","biz","util"],function(a,b,d,c){function k(a,c){for(var c=c||0,b=[],d=0,e=a.length;d<e;d++)b.push(a[d].split("_")[c]);return b.join(",")}function f(a){a=a||window.document.domain;0===a.indexOf("www.")&&(a=a.substr(4));"."===a.charAt(a.length-1)&&(a=a.substring(0,a.length-1));var c=a.match(RegExp("([a-z0-9][a-z0-9\\-]*?\\.(?:com|cn|net|org|gov|info|la|cc|co|jp|us|hk|tv|me|biz|in|be|io|tk|cm|li|ru|ws|hn|fm|tw|ma|in|vn|name|mx|gd|im)(?:\\.(?:cn|jp|tw|ru|th))?)$","i"));return c?
c[0]:a}var g=window,i=g.document,j=g.screen,h=g.navigator,e=+new Date,o=[{key:"di",value:function(a){return k(a.id)}},{key:"dcb",value:s("BAIDU_DUP_define")},{key:"dtm",value:s("BAIDU_DUP2_SETJSONADSLOT")},{key:"dbv",value:function(){var a=c.W;return a.Pa?"1":a.qa?"2":"0"}},{key:"dci",value:function(c){for(var b="-1",d={fill:"0",fillOnePiece:"1",fillAsync:"2",preload:"3"},e=0;e<c.id.length;e++){var i=a.z(c.id[e]);if(i){var i=i.stack,f=i.length;if(1<=f){b=d[i[f-1]];break}}}return b}},{key:"dri",value:function(a){return k(a.id,
1)}},{key:"dis",value:function(){var a=0;c.a.t(g)&&(a+=1);c.a.C(g,g.top)&&(a+=2);var b=c.style.p(),d=c.style.o();if(40>b||10>d)a+=4;return a}},{key:"dai",value:function(c){return a.K(c.id).join(",")}},{key:"dds",value:function(){var a=c.data.d("dds");return c.lang.ia(a)}},{key:"drs",value:function(){var a={uninitialized:0,loading:1,loaded:2,interactive:3,complete:4};try{return a[i.readyState]}catch(c){return-1}}},{key:"dvi",value:s("1430984165")},{key:"ltu",n:m,value:function(){var a=c.url.O(function(a){var b=
c.style.p(a),a=c.style.o(a);return 400<b&&120<a?m:r});0<a.indexOf("cpro_prev")&&(a=a.slice(0,a.indexOf("?")));return a}},{key:"liu",n:m,value:function(){return c.a.t(g)?i.URL:""}},{key:"ltr",n:m,value:function(){var a=c.a.L(),b="";try{b=a.opener?a.opener.document.location.href:""}catch(d){}return b||a.document.referrer}},{key:"lcr",n:m,value:function(a){if(a&&0!==a.id.length&&-1<a.id[0].indexOf("u"))return"";var a=i.referrer,b=a.replace(/^https?:\/\//,""),b=b.split("/")[0],b=b.split(":")[0],b=f(b),
d=f(),e=c.cookie.get("BAIDU_DUP_lcr");if(e&&d===b)return e;return d!==b?(c.cookie.set("BAIDU_DUP_lcr",a,{domain:d}),a):""}},{key:"ps",value:function(c){return a.r(c.id).join(",")}},{key:"psr",value:function(){return[j.width,j.height].join("x")}},{key:"par",value:function(){return[j.availWidth,j.availHeight].join("x")}},{key:"pcs",value:function(){return[c.style.p(),c.style.o()].join("x")}},{key:"pss",value:function(){return[c.style.ca(),c.style.ba()].join("x")}},{key:"pis",value:function(){return(c.a.t(g)?
[c.style.p(),c.style.o()]:[-1,-1]).join("x")}},{key:"cfv",value:function(){var a=0;if(h.plugins&&h.mimeTypes.length){var c=h.plugins["Shockwave Flash"];c&&c.description&&(a=c.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")+".0")}else if(g.ActiveXObject&&!g.opera)for(c=10;2<=c;c--)try{var b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+c);b&&(a=b.GetVariable("$version").replace(/WIN/g,"").replace(/,/g,"."))}catch(d){}return parseInt(a,10)}},{key:"ccd",value:function(){return j.colorDepth||
0}},{key:"chi",value:function(){return g.history.length||0}},{key:"cja",value:function(){return h.javaEnabled().toString()}},{key:"cpl",value:function(){return h.plugins.length||0}},{key:"cmi",value:function(){return h.mimeTypes.length||0}},{key:"cce",value:function(){return h.cookieEnabled||0}},{key:"col",value:function(){return(h.language||h.browserLanguage||h.systemLanguage).replace(/[^a-zA-Z0-9\-]/g,"")}},{key:"cec",value:function(){return(i.characterSet?i.characterSet:i.charset)||""}},{key:"cdo",
value:function(){var a=window.orientation;a===l&&(a=-1);return a}},{key:"tsr",value:function(){var a=0,c=+new Date;e&&(a=c-e);return a}},{key:"tlm",value:function(){return Date.parse(i.lastModified)/1E3}},{key:"tcn",value:function(){return Math.round(+new Date/1E3)}},{key:"tpr",value:function(a){var a=a&&a.max_age?a.max_age:24E4,c=(new Date).getTime(),b,d;try{b=!!window.top.location.toString()}catch(e){b=r}d=b?window.top:window;(b=d.BAIDU_DUP2_pageFirstRequestTime)?c-b>=a&&(b=d.BAIDU_DUP2_pageFirstRequestTime=
c):b=d.BAIDU_DUP2_pageFirstRequestTime=c;return b||""}},{key:"_preview",value:function(a){return b.Ca(k(a.id))}},{key:"dpt",value:function(){var a="none";b.da()&&(a="union");return a}},{key:"coa",n:m,value:function(a){var b=a.id,a={cpro_w:"rsi0",cpro_h:"rsi1"},b=b[0].split("_")[0],d={},e=r,i=c.data.d("#novaOpenApi");if(i&&b&&i[b]){var e=m,b=i[b],f;for(f in b)f&&b.hasOwnProperty(f)&&"undefined"!==typeof b[f]&&(d[f]=encodeURIComponent(b[f]).toString())}e&&(d.c01=1);var e=f="",h;for(h in d)h&&d.hasOwnProperty(h)&&
"undefined"!==typeof d[h]&&(e=d[h],"cpro_h"===h&&(c.data.f("setCoaHeight",m),e=parseInt(e,10)||125),"cpro_w"===h&&(c.data.f("setCoaWidth",m),e=parseInt(e,10)||125),f+="&"+(a[h]?a[h]:h)+"="+e);return f=f.slice(1)}},{key:"ti",n:m,value:function(){return c.a.Z()}},{key:"_unionpreview",value:function(){return b.Da()}},{key:"baidu_id",value:s("")},{key:"_orientation",value:function(){return d.ya()}}];return{get:function(a,c){for(var b=[],d=0,e=o.length;d<e;d++){var i;try{var f=o[d],h=f.key,g=f.n,j=f.value,
j="function"===typeof j?j(a):j,j=g?encodeURIComponent(j):j;if(c&&c===h)return j;i=h&&0!==h.indexOf("_")?h+"="+j:j}catch(k){i=encodeURIComponent(k.toString()),i=i.slice(0,100)}i&&b.push(i)}b=b.join("&");return b.slice(0,2048)}}});
R("request",["param","slot","util"],function(a,b,d){R("request!",[],{name2url:function(c){return"http://cb.baidu.com/ecom?"+a.get({id:c.split(",")})}});R("batch!",[],{name2url:function(c){return"http://cb.baidu.com/ecom?"+a.get({id:c.split(",")})}});return{send:function(a,k,f){if(!a||!k||f===l)return r;var g=[];if("array"!==d.lang.b(a))b.u(a,"request"),g=["request!"+a];else{for(g=0;g<a.length;g++)b.u(a[g],"request");g=1===a.length?["request!"+a[0]]:["batch!"+a.join(",")]}Q(g,k,f);return m}}});
R("control",["slot","request","preview","util"],function(a,b,d,c){function k(b,d,f){var e=d.deps,g=d.data,k=a.$(b);f&&!k?a.k(b,"HolderNotFound"):e&&(0>e[0].indexOf("clb/")&&a.u(b,"finish"),Q(e,function(d){if("object"===c.lang.b(g)){g.id=b;if(d.hasOwnProperty("validate"))try{var f=d.validate(g);f!==m&&c.log.H({data:{type:f||"ResponseError",errorPainter:e[0],id:b,slotType:g._stype,materialType:g._isMlt,html:!!g._html}})}catch(h){a.k(b,"validateException")}if(d.hasOwnProperty("render"))try{a.u(b,"render"),
d.render(g,k)}catch(j){a.k(b,"RenderException")}else a.k(b,"RenderNotFound")}else a.k(b,"ResponseFormatError")},f))}function f(d,f,h){if(!d)return r;var h=h||"",e=a.add(d),d=e.ids[0]||e.preloadIds[0];c.data.f("timestampWathcer"+d,u);if(!d)return r;var g=a.sa(d,f);a.I(d,f);a.create(d,f,h);e.ids.length?b.send(d,function(b){a.S(d,b);k(d,b,g)},g):e.preloadIds.length&&(f=a.z(d).response,k(d,f,g));return m}function g(b){for(var c=0,d=b+"_"+c;0!==a.K([d])[0];){var e=a.z(d);if((e=e&&e.response)&&0===e.deps[0].indexOf("clb/")){var f=
e.data,e=f._isMlt;(0===e&&""!==f._html||e===r&&f._fxp)&&a.u(d,"finish",0)}d=b+"_"+ ++c}if(b!==l&&(b=(c=window.BAIDU_CLB_SLOTS_MAP)&&c[b],b!==l&&(e=b._isMlt,0===e&&""!==b._html||e===r&&b._fxp)))b._done=r}window.BAIDU_CLB_prepareMoveSlot=g;return{fill:function(a){return f(a,"fill")},J:function(a,b){return f(a,"fillAsync",b)},La:function(){function f(d){b.send(d,function(b){if("array"===c.lang.b(b)){if(b&&b.length===d.length)for(var e=0;e<d.length;e++)a.S(d[e],b[e])}else"object"===c.lang.b(b)&&b&&1===
d.length&&a.S(d[0],b)},r)}var g=c.lang.l(arguments),g=c.lang.unique(g),h=d.d();if(h)for(var e=0,k=g.length;e<k;e++)g[e]==h.ja&&(g.splice(e,1),e--);for(g=a.add(g).ids;g.length;){h=g.splice(0,16);for(e=0;e<h.length;e++)a.I(h[e],"preload");f(h)}},Ma:g}});
R("global",["control","biz","util","preview"],function(a,b,d,c){function k(a){a=a.split(".");return h[a[0]]+a[1]}function f(){var a=j.BAIDU_DUP;if(!("object"===d.lang.b(a)&&a.push)){if("array"===d.lang.b(a)&&a.length)for(var b=0;b<a.length;b++)g(a[b]);j.BAIDU_DUP=l;d.data.m("BAIDU_DUP",{push:g});d.data.m("BAIDU_DUP_proxy",function(a){if(a)return function(){try{return g([a].concat(d.lang.l(arguments)))}catch(b){0<ga--&&d.log.H({data:{type:"ExecuteException",errorName:a,args:d.lang.l(arguments).join("|"),
isQuirksMode:"CSS1Compat"!==document.compatMode,documentMode:document.documentMode||"",readyState:document.readyState||"",message:b.message}})}}});for(b in o)b&&d.lang.B.call(o,b)&&d.data.m(b,j.BAIDU_DUP_proxy(b));i()}}function g(a){if("array"!==d.lang.b(a))return r;var b=a.shift();d.data.U("apiCount",b);return(b=o[b]||n[b]||r)&&b.apply(q,a)}function i(){function a(b){for(var c=0,d=y.length;c<d;c++)if(0===b.indexOf(y[c]))return m;return r}d.data.m("BAIDU_DUP_require",function(b){for(var c=0,d=b.length;c<
d;c++)if(a(b[c]))return;Q.apply(q,arguments)});d.data.m("BAIDU_DUP_define",function(b,c){for(var d=0,e=c.length;d<e;d++)if(a(c[d]))return;R.apply(q,arguments)})}var j=window,h={clb:"BAIDU_CLB_",dan:"BAIDU_DAN_",nova:"cpro",dup:"BAIDU_DUP_"},e=[{h:["clb.fillSlot","clb.singleFillSlot","clb.fillSlotWithSize"],i:["fill"],g:a.fill},{h:["clb.fillSlotAsync"],i:["fillAsync"],g:a.J},{h:["clb.preloadSlots"],i:["preload"],g:a.La},{h:["clb.prepareMoveSlot"],i:["prepareMove"],g:a.Ma},{h:["clb.addOrientation"],
i:["addOrientation"],g:b.V},{h:["clb.addOrientationOnce"],i:["addOrientationOnce"],g:b.ma},{h:["clb.setOrientationOnce"],i:["setOrientationOnce"],g:b.Ra},{h:["clb.setConfig"],i:["putConfig"],g:d.data.Oa},{h:["clb.addSlot","clb.enableAllSlots","clb.SETHTMLSLOT"],i:[],g:d.lang.fa},{h:["dup.addSlotStatusCallback"],i:[],g:b.na}],e=function(a){for(var b={},c={},d=0;d<a.length;d++){for(var e=a[d],f=e.h,g=e.i,e=e.g;f.length;)b[k(f.shift())]=e;for(;g.length;)c[g.shift()]=e}return{Ja:b,Na:c}}(e),o=e.Ja,n=
e.Na;return{Ea:function(){var e=d.data.q(k("clb.ORIENTATIONS"));if(e)for(var g in e)Object.prototype.hasOwnProperty.call(e,g)&&b.V(g,e[g]);d.data.f("#novaOpenApi",d.data.q("cproStyleApi"));var h=d.data.q("cproArray");if(h)for(var e=0,i=h.length;e<i;e++)h[e]&&h[e].id&&a.J(h[e].id,"cpro_"+h[e].id);if(h=d.data.q("cpro_mobile_slot")){e=0;for(i=h.length;e<i;e++){var j=h[e],n=j.id,o=d.data.d("#novaOpenApi")||{};o[n]||(o[n]={});for(g in j)g&&"id"!==g&&j.hasOwnProperty(g)&&(o[n][g]=j[g]);d.data.f("#novaOpenApi",
o);h[e]&&h[e].id&&a.J(h[e].id,"cpro_"+h[e].id)}}if(g=d.data.q("cpro_id"))c.da(g)&&(c.Ta(g),g="u0"),a.fill(g);a.fill(d.data.q(k("clb.SLOT_ID")));f()}}});R("logService",["util/lang","util/event"],function(a,b){b.bind(window,"load",function(){Q(["detect"],a.fa,m)})});
R("fingerprint",["util/storage","util/event","util/browser","util/data","param"],function(a,b,d,c,k){var f=window,g=r;d.s?6<=d.s&&(g=m):a.pa()&&(g=m);0<=f.location.href.indexOf("wa.kuwo.cn")||(g&&(c.d("isFPLoaded",m)===m?g=r:c.f("isFPLoaded",m,m)),g&&b.bind(f,"load",function(){var a=f.document,b=a.body,c="http://pos.baidu.com/wh/o.htm?ltr="+k.get({},"ltr"),d=a.createElement("div");d.id="BAIDU_DUP_fp_wrapper";d.style.position="absolute";d.style.left="-1px";d.style.bottom="-1px";d.style.zIndex=0;d.style.width=
0;d.style.height=0;d.style.overflow="hidden";d.style.visibility="hidden";d.style.display="none";a=a.createElement("iframe");a.id="BAIDU_DUP_fp_iframe";a.src=c;a.style.width=0;a.style.height=0;a.style.visibility="hidden";a.style.display="none";try{d.insertBefore(a,d.firstChild),b&&b.insertBefore(d,b.firstChild)}catch(g){}}))});R("replacement",["util"],function(a){function b(){var d=a.url.O(),c=a.url.aa(d,ha,m);b=function(){return c};return c}return{za:function(){return b()}}});
Q(["replacement"],function(a){(a=a.za())?Q([a]):(Q(["global"],function(a){a.Ea()}),Q(["logService"]),Q(["fingerprint"]))});
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("detect",["api"],function(a){function b(b){b.url="";b.host=window.location.hostname;b.from="DUP";a.sendLog({data:b,eb:"now"})}try{setTimeout(function(){var c=a.getSlots(),d;for(d in c){var f=c[d],g=f.response,i=r;if("object"!==a.getType(g))i=m;else{var i=m,j;for(j in g)if(Object.prototype.hasOwnProperty.call(g,j)){i=r;break}}var h=f.status,f=f.stack;i?b({type:"preload"===f[0]?"preloadFail":"loadFail",id:d}):!h.render&&!h.finish&&b({type:"renderFail",
id:d,error:"preload"===f[0]?"PreloadNotFilled":"NotFilled",empty:!(!g.data||!g.data._html)})}},0)}catch(d){}});
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("viewWatch",["util","param"],function(a,b){function d(){var b=+new Date,d=500;x===i&&M&&(d=b-M);M=b;for(var h in n)if(o.call(n,h)){x===f&&(x=g);var j=n[h];j.G&&(j.Q+=d);j.F&&(j.P+=d);j.R=b-j.timestamp;if(x===i)H&&(j.w+=b-j.D);else if(72E5<=j.R)c(r);else{var k=j=l,p=l;for(p in n)if(o.call(n,p)){var w=n[p];if(H){var v=a.a.c(w.Va);if(!v)break;try{var t=e.p(B),A=e.o(B),I=e.r(v);w.top=I.top;w.left=I.left;var X=e.Ba(B),Y=e.Aa(B),Z=e.N(v),$=e.M(v),aa=I.top-
X+0.35*$,ba=I.left-Y+0.35*Z;w.G=0<aa&&aa<A&&0<ba&&ba<t;var pa=Z*$,ca=e.r(v),N=ca.top-X,O=ca.left-Y,da=e.N(v),ea=e.M(v),fa=v=0,v=0>N?Math.max(N+ea,0):Math.min(ea,Math.max(A-N,0)),fa=0>O?Math.max(O+da,0):Math.min(da,Math.max(t-O,0));j=fa;k=v;w.F=k*j>0.5*pa}catch(ra){w.G=r,w.F=r}}else w.G=r,w.F=r}}}}function c(b){clearInterval(t);var c=document.domain.toLowerCase();if(!(-1<c.indexOf("autohome.com.cn")||-1<c.indexOf("sina.com.cn")||-1<c.indexOf("pconline.com.cn")||-1<c.indexOf("pcauto.com.cn")||-1<c.indexOf("pclady.com.cn")||
-1<c.indexOf("pcgames.com.cn")||-1<c.indexOf("pcbaby.com.cn")||-1<c.indexOf("pchouse.com.cn")||-1<c.indexOf("xcar.com.cn")))if(x!==g)x=i;else{x=i;d();var c=r,e;for(e in n)if(e&&n.hasOwnProperty(e)&&n[e]){var f=n[e];"block"===f.Ha&&(c=m);f.total=p;a.log.H({url:k(f)})}if(b&&c)if(b=+new Date,j.s)for(c=b+200;c>+new Date;);else{e=1E5;for(c=0;c<e;c++);c=+new Date;e=Math.min(200*e/(c-b),1E7);for(c=0;c<e;c++);}}}function k(a){var c=["tu="+a.id,"word="+b.get(l,"ltu"),"if="+b.get(l,"dis"),"aw="+a.width,"ah="+
a.height,"pt="+a.R,"it="+a.Q,"vt="+a.P,"csp="+A,"bcl="+a.ra,"pof="+a.Qa,"top="+a.top,"left="+a.left,"total="+a.total];return a.url+(a.Y?a.Y+"&":"")+c.join("&")}var f=1,g=2,i=3,j=a.W,h=a.event.bind,e=a.style,o=a.lang.B,n=[],p=0,t=0,x=f,H=m,M=0,A=[1E4<screen.availWidth?0:screen.availWidth,1E4<screen.availHeight?0:screen.availHeight].join(),B=window;a.a.t(window)&&!a.a.C(window)&&(B=window.top);t=setInterval(d,500);(function(){function a(){var b=+new Date,c;for(c in n)if(o.call(n,c)){var d=n[c];d.w+=
b-d.D;d.D=b}H=r}function b(){var a=+new Date,c;for(c in n)o.call(n,c)&&(n[c].D=a);H=m}j.s?(h(document,"focusin",b),h(document,"focusout",a)):(h(window,"focus",b),h(window,"blur",a))})();h(window,"beforeunload",c);return{register:function(b){var c=+new Date,d=b.id,f=b.wrapperId,g=b.url||"http://eclick.baidu.com/a.js?",h=b.logType||"storage",b=b.extra||"";if(f&&!n[f]){var i=a.a.c(f);if(i){var j=e.r(i);n[f]={id:d,Va:f,url:g,Ha:h,Y:b,timestamp:c,Q:0,G:r,P:0,F:r,R:0,w:0,D:c,top:j.top,left:j.left,hb:A,
opacity:e.xa(i),ra:[e.p(),e.o()].join(),Qa:[e.ca(),e.ba()].join(),width:e.N(i),height:e.M(i)};p++}}},getWatchCount:function(){return p}}});})();
